---

- name: ensure apache is installed
  apt:
    name: apache2
    state: latest
    update_cache: yes
  become: yes
  notify:
    - enable apache
    - start apache

- name: change index file
  template: 
    src: index.html
    dest: /var/www/html/index.html
  become: yes
  notify:
    - restart apache