---

- name: ensure PHP and its needed modules are installed
  apt: name={{ item }} state=latest
  with_items:
    - php7.0
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-gd
    - php7.0-opcache
    - php7.0-pspell
    - php7.0-json
    - php7.0-xml
    - php7.0-xmlrpc
    - php7.0-mysql
    - php7.0-mbstring
    - php7.0-ldap
    - php7.0-intl
    - php7.0-soap
    - php7.0-zip
    - libapache2-mod-php7.0
  become: yes
  notify:
    - restart apache
